name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [10, 12, 14, 20]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm install

    - name: Test
      if: matrix.nodejs <= 20
      run: npm test

    - name: Coverage
      if: matrix.nodejs > 20
      run: |
        npm install -g c8
        c8 npm test
        c8 report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
